# -*- coding: utf-8 -*-
"""KNNeighbour.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hpQWaDWSBckxxPsMP2n-lAJvkMChGqkh
"""

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
import numpy as np
from sklearn.metrics import confusion_matrix,classification_report

df = pd.read_csv('/content/iris_csv.csv')
df

x = df.drop('class',axis=1)
y = df['class']
x,y

y.unique()

le  = LabelEncoder()
y = le.fit_transform(y)
y

xtr,xte,ytr,yte = train_test_split(x,y,test_size=0.2,random_state=42)

xte.shape,xtr.shapem

scaler = StandardScaler()
xtr = scaler.fit_transform(xtr)
xte = scaler.fit_transform(xte)

np.mean(xtr),np.std(xtr)
np.mean(xte),np.std(xte)

model = KNeighborsClassifier(n_neighbors=1)
model.fit(xtr,ytr)

ypre = model.predict(xte)
ypre

model.score(xtr,ytr),model.score(xte,yte)

z = confusion_matrix(yte,ypre)
print(z)

c = classification_report(yte,ypre)
print(c)