# -*- coding: utf-8 -*-
"""MultiVariat_prc1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mrv-A4efVD2t8I5ScyChjWz42S22Np9Q
"""

import pandas as pd
from sklearn import model_selection

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import Ridge
from sklearn.metrics import  mean_squared_error,mean_absolute_error,r2_score

df =  pd.read_csv('/content/Boston.csv')
df

df.isnull().sum()
df.info

df.corr()

x = df.drop('medv',axis=1).values
y = df['medv'].values
x,y

xtr,xte,ytr,yte = train_test_split(x,y,test_size=0.1,random_state=42)

xtr.shape,xte.shape

reg = linear_model.Ridge(alpha=0.2)
reg.fit(xtr,ytr)

ypre = reg.predict(xte)
msel=mean_squared_error(yte,ypre)
mael = mean_absolute_error(yte,ypre)
rs = r2_score(yte,ypre)
print(msel)
print(mael)
print(rs)

reg = linear_model.Ridge(alpha=0.5)
reg.fit(xtr,ytr)

ypre = reg.predict(xte)
msel=mean_squared_error(yte,ypre)
mael = mean_absolute_error(yte,ypre)
rs = r2_score(yte,ypre)
print(msel)
print(mael)
print(rs)