# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lGH7vFGzxlceTjtEarM93AVz970fHCu4
"""

import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

cancer = load_breast_cancer()

df = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
df

scaler = StandardScaler()
scaler.fit(df)

scaledata = scaler.transform(df)

pca = PCA(n_components=2)
pca.fit(scaledata)

xpca = pca.transform(scaledata)
xpca.shape

plt.figure(figsize=(8,6))
plt.scatter(xpca[:,0],xpca[:,1],c=cancer['target'],cmap='plasma')
plt.xlabel('First principal component')
plt.ylabel('Second Principal Component')

pca.components_